alias ls="ls -A -h --color=auto"
alias ll="ls -l"
alias c="code ."
alias prd="pnpm run dev"
alias px="pnpm exec"
alias n="nvim"
alias zshrc="nvim $DOTFILES/zsh/.sp.zsh"
alias aliases="nvim $DOTFILES/zsh/.alias.zsh"
alias funcs="nvim $DOTFILES/zsh/.functions.zsh"
alias wez="nvim $DOTFILES/wezterm/.wezterm.lua"
alias nvimconf="cd $DOTFILES/nvim/.config/nvim/ && nvim"
